# Generated by Django 4.2.6 on 2023-10-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название картинки')),
                ('image', models.ImageField(upload_to='main/static/main/img/carousel', verbose_name='Фотография кошки/собаки')),
                ('date', models.DateField(verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Cats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, verbose_name='Кличка кота')),
                ('image', models.ImageField(upload_to='main/static/main/img/cats', verbose_name='Фотография кота')),
                ('full_text', models.TextField(verbose_name='Информация о коте')),
                ('date', models.DateField(verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, verbose_name='Кличка собаки')),
                ('image', models.ImageField(upload_to='main/static/main/img/dogs', verbose_name='Фотография собаки')),
                ('full_text', models.TextField(verbose_name='Информация о собаке')),
                ('date', models.DateField(verbose_name='Дата публикации')),
            ],
        ),
    ]
